apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - image: aramos90/udagram-api-user:v1
        name: backend-user
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL 
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: NODE_TLS_REJECT_UNAUTHORIZED
        - name: PGSSLMODE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: PGSSLMODE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret